[cursor.style]
shape = "Beam"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[terminal]
shell = "/bin/zsh"
